package Main;

import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Laporan
     */
    public Laporan() {
        initComponents();
    }
   private void load_table(){
        //menampilkan data database kedalam tabel
        try {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggal=String.valueOf(fm.format(jDateChooser1.getDate()));
            String tanggal1=String.valueOf(fm.format(jDateChooser2.getDate()));
            String sql = "SELECT SUM(detail_penjualan.jumlah*produk.harga_jual) AS total_harga\n" +
            "FROM detail_penjualan JOIN produk ON detail_penjualan.kode_produk=produk.kode_produk "
                    + "JOIN penjualan ON detail_penjualan.kode_penjualan=penjualan.kode_penjualan\n" +
            "WHERE penjualan.waktu <= '"+tanggal1+ "' AND penjualan.waktu >= '"+tanggal+"'"+
            "ORDER BY total_harga" ;
            java.sql.Connection conn=(Connection)Konfigurasi.konfigurasiDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                jTextField1.setText("Rp."+res.getString(1));
            }
        } catch (Exception e){}
    }
    private void load_table1(){
        //menampilkan data database kedalam tabel
        try {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggal=String.valueOf(fm.format(jDateChooser1.getDate()));
            String tanggal1=String.valueOf(fm.format(jDateChooser2.getDate()));
            String sql = "SELECT Sum(jumlah*produk.harga_beli) AS total_harga" +
            " FROM detail_pembelian JOIN produk ON detail_pembelian.kode_produk=produk.kode_produk "
                    + "JOIN pembelian ON detail_pembelian.kode_pembelian=pembelian.kode_pembelian"+
            " WHERE pembelian.waktu >= '"+tanggal+ "' AND pembelian.waktu <= '"+tanggal1+"'"+
            " ORDER BY total_harga DESC";
            java.sql.Connection conn=(Connection)Konfigurasi.konfigurasiDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                jTextField1.setText("Rp."+res.getString(1));
            }
        } catch (Exception e){}
    }
private void cetak(){
    try {
        jTableLaporan.print();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tabel Kosong, Silahkan inputkan data kembali");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLaporan = new javax.swing.JTable();
        btn_cetakpenjualan = new javax.swing.JButton();
        btn_cetakpembelian = new javax.swing.JButton();
        btn_cekPenjualan = new javax.swing.JButton();
        btn_cekPembelian = new javax.swing.JButton();
        logout_btn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        lblproduk = new javax.swing.JLabel();
        lblpembelian = new javax.swing.JLabel();
        lblkaryawan = new javax.swing.JLabel();
        lbllaporan = new javax.swing.JLabel();
        lblpenjualan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Filter Tanggal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, 30));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 190, -1));

        jTableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLaporan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 700, 360));

        btn_cetakpenjualan.setBackground(new java.awt.Color(0, 153, 153));
        btn_cetakpenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cetakpenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetakpenjualan.setText("Cetak Laporan Penjualan");
        btn_cetakpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakpenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetakpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 170, 50));

        btn_cetakpembelian.setBackground(new java.awt.Color(0, 153, 153));
        btn_cetakpembelian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cetakpembelian.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetakpembelian.setText("Cetak Laporan Pembelian");
        btn_cetakpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakpembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetakpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 170, 50));

        btn_cekPenjualan.setBackground(new java.awt.Color(0, 153, 153));
        btn_cekPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cekPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btn_cekPenjualan.setText("Cek Laporan Penjualan");
        btn_cekPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekPenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cekPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 80, 160, 50));

        btn_cekPembelian.setBackground(new java.awt.Color(0, 153, 153));
        btn_cekPembelian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cekPembelian.setForeground(new java.awt.Color(255, 255, 255));
        btn_cekPembelian.setText("Cek Laporan Pembelian");
        btn_cekPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekPembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cekPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 80, 160, 50));

        logout_btn1.setBackground(new java.awt.Color(0, 102, 102));
        logout_btn1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        logout_btn1.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn1.setText("LOGOUT");
        logout_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(logout_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 130, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Total :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 140, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Laporan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 710));

        lblhome.setText("Home");
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
        });
        jPanel1.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 90));

        lblproduk.setText("Produk");
        lblproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblprodukMouseClicked(evt);
            }
        });
        jPanel1.add(lblproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 70));

        lblpembelian.setText("Pembelian");
        lblpembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpembelianMouseClicked(evt);
            }
        });
        jPanel1.add(lblpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 70));

        lblkaryawan.setText("Karyawan");
        lblkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkaryawanMouseClicked(evt);
            }
        });
        jPanel1.add(lblkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 100, 70));

        lbllaporan.setText("Laporan");
        lbllaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllaporanMouseClicked(evt);
            }
        });
        jPanel1.add(lbllaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 80, 70));

        lblpenjualan.setText("Penjualan");
        lblpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpenjualanMouseClicked(evt);
            }
        });
        jPanel1.add(lblpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakpenjualanActionPerformed
        // TODO add your handling code here:
        cetak();
    }//GEN-LAST:event_btn_cetakpenjualanActionPerformed

    private void btn_cetakpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakpembelianActionPerformed
        // TODO add your handling code here:
        cetak();
    }//GEN-LAST:event_btn_cetakpembelianActionPerformed

    private void btn_cekPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekPenjualanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Penjualan");
        model.addColumn("Nama Produk");
        model.addColumn("Waktu");
        model.addColumn("Jumlah");
        model.addColumn("Total Harga");

        //menampilkan data database kedalam tabel

        try {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggal=String.valueOf(fm.format(jDateChooser1.getDate()));
            String tanggal1=String.valueOf(fm.format(jDateChooser2.getDate()));
            String sql = "SELECT penjualan.kode_penjualan, produk.nama_produk, penjualan.waktu, "
            + "detail_penjualan.jumlah, detail_penjualan.jumlah*produk.harga_jual AS total_harga\n" +
            "FROM detail_penjualan JOIN produk ON detail_penjualan.kode_produk=produk.kode_produk "
            + "JOIN penjualan ON detail_penjualan.kode_penjualan=penjualan.kode_penjualan\n" +
            "WHERE penjualan.waktu <= '"+tanggal1+ "' AND penjualan.waktu >= '"+tanggal+"'"+
            "ORDER BY total_harga DESC";
            System.out.println(sql);
            java.sql.Connection conn=(Connection)Konfigurasi.konfigurasiDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2), res.getString(3),
                    res.getString(4), res.getString(5)});
        }

        jTableLaporan.setModel(model);
        } catch (Exception e){}
        load_table();
    }//GEN-LAST:event_btn_cekPenjualanActionPerformed

    private void btn_cekPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekPembelianActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Pembelian");
        model.addColumn("Nama Produk");
        model.addColumn("Waktu");
        model.addColumn("Jumlah");
        model.addColumn("Total Harga");

        //menampilkan data database kedalam tabel
        try {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggal=String.valueOf(fm.format(jDateChooser1.getDate()));
            String tanggal1=String.valueOf(fm.format(jDateChooser2.getDate()));
            String sql = "SELECT pembelian.kode_pembelian, produk.nama_produk, pembelian.waktu, "
            + "detail_pembelian.jumlah, detail_pembelian.jumlah*produk.harga_beli AS total_harga"+
            " FROM detail_pembelian JOIN produk ON detail_pembelian.kode_produk=produk.kode_produk "
            + "JOIN pembelian ON detail_pembelian.kode_pembelian=pembelian.kode_pembelian"+
            " WHERE pembelian.waktu >= '"+tanggal+ "' AND pembelian.waktu <= '"+tanggal1+"'"+
            " ORDER BY total_harga DESC";
            java.sql.Connection conn=(Connection)Konfigurasi.konfigurasiDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2), res.getString(3),
                    res.getString(4), res.getString(5)});
        }

        jTableLaporan.setModel(model);
        } catch (Exception e){}
        load_table1();
    }//GEN-LAST:event_btn_cekPembelianActionPerformed

    private void lblprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblprodukMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Produk().setVisible(true);
    }//GEN-LAST:event_lblprodukMouseClicked

    private void lblpembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpembelianMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Pembelian().setVisible(true);
    }//GEN-LAST:event_lblpembelianMouseClicked

    private void lblkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkaryawanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Karyawan().setVisible(true);
    }//GEN-LAST:event_lblkaryawanMouseClicked

    private void lbllaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllaporanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Laporan().setVisible(true);
    }//GEN-LAST:event_lbllaporanMouseClicked

    private void lblpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpenjualanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Penjualan().setVisible(true);
    }//GEN-LAST:event_lblpenjualanMouseClicked

    private void logout_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logout_btn1ActionPerformed

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_lblhomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cekPembelian;
    private javax.swing.JButton btn_cekPenjualan;
    private javax.swing.JButton btn_cetakpembelian;
    private javax.swing.JButton btn_cetakpenjualan;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLaporan;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblkaryawan;
    private javax.swing.JLabel lbllaporan;
    private javax.swing.JLabel lblpembelian;
    private javax.swing.JLabel lblpenjualan;
    private javax.swing.JLabel lblproduk;
    private javax.swing.JButton logout_btn1;
    // End of variables declaration//GEN-END:variables
}
